### ISSUE TITLE
Fix ToC of coding standards

### ISSUE THREAD

**Issue by damithc** [oss-generic/process#1]
The Table of Content links in the published version at https://oss-generic.github.io/process/codingstandards/coding-standards-java.html don't work.

**Comment by damithc** [comment]
Same problem in the html coding standard.

**Comment by damithc** [comment]
Closing this as there is a PR for the other copy of this issue.

**Comment by damithc** [comment]
@wkurniawan07 is this a problem with the markdown->html conversion script? (links work in markdown file but not in the html file)

**Comment by wkurniawan07** [comment]
I'll have a look, but need to re-familiarize with the code first.

**Comment by wkurniawan07** [comment]
On an unrelated note, why is this repo not under `nus-oss` instead?

**Comment by damithc** [comment]
This org (oss-generic) contains generic resources that can be used outside NUS projects.

**Comment by wkurniawan07** [comment]
Found the issue. Unlike the GitHub website, the GitHub API alone does not automatically attach anchors to headings `h1`, `h2`, `h3` etc.

**Comment by damithc** [comment]
I see. Guess we have to add anchors manually then?

**Comment by wkurniawan07** [comment]
Yes, I believe so.
