### ISSUE TITLE
Switch statement example does not follow whitespace guideline 

### ISSUE THREAD

**Issue by ZhangYiJiang** [oss-generic/process#3]
The `switch` statement layout example does not have whitespace surrounding the colon

``` java
switch (condition) {
case ABC:
    statements;
    // Fallthrough
case DEF:
    statements;
    break;
case XYZ:
    statements;
    break;
default:
    statements;
    break;
}
```

but a bit further down this style is discouraged - 

> - Colons should be surrounded by white space.

**Comment by damithc** [comment]
This contradiction exists in Google's Java coding standard too.

**Comment by ZhangYiJiang** [comment]
I tried looking for it but I can't find it. https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace does not mention `switch` statement `case`s at all.

**Comment by damithc** [comment]
What I meant is their `switch` example doesn't have a space before `:` either.
So I think we should clarify in our style guide that 'colon should be surrounded by spaces *when it is used as a binary/ternary operator*'. `switch` is not such a use of `:` and most examples I find (e.g. default code style of Eclipse/IDEA) don't have a space around the `:` in `case x:`
