### ISSUE TITLE
Standardize how to refer to Java class variables and methods from text

### ISSUE THREAD

**Issue by PierceAndy** [oss-generic/process#51]
It would be good to have a standard for referring to class methods in commit messages for ease of reviewing.

I propose `Class#method()`.

It is short, so it takes up less characters in the commit message's subject line.
Alternatives, such as `Class::method()` or `Class#method(Type, Type)` take up more characters without necessarily being more informative.

**Comment by damithc** [comment]
How about this?:
Use `package.class#variable` and `package.class#method(paramTypes):returnType` format but omit `package`, `paramTypes`, and `:returnType` if doing so will not cause ambiguities and the details are
not pertinent to the context.

e.g.
* `Person#name`
* `Person#getName()` 
* `Person#getName():String` 
* `Person#setName()` 
  > parameters omitted 
* `Person#getName(String, int)` 
   > parameter types specified to disambiguate from other overloaded methods.
* `data.Person#toString()`
