### ISSUE TITLE
Format: recommend using a scope prefix for commit message subject line

### ISSUE THREAD

**Issue by PierceAndy** [oss-generic/process#52]
It would be good to have standard for the subject line of commit messages.

I propose `Class: do something to method()`.

It makes it easier to see which class is primarily being modified in the commit, and which method is being affected, and how it is being affected.

**Comment by damithc** [comment]
More generally, use format `scope: change` e.g. `GUI tests: remove extra empty lines`
The _scope prefix_ is recommended but not compulsory.

Other things that we can add:
* mention: shoot for 50 characters, but consider 72 the hard limit.
