### ISSUE TITLE
QuestionsIssuesPrs.md: make PR workflow steps linkable 

### ISSUE THREAD

**Issue by chao1995** [oss-generic/process#81]
The instructions for how to use canihasreview is currently only available in https://github.com/oss-generic/process/blob/master/docs/QuestionsIssuesPrs.md#pr-workflow, but it is a 6th step inside a list, so we cannot get a link to it.

**Comment by damithc** [comment]
We can move that part to the [How to doc](https://github.com/oss-generic/process/blob/master/docs/HowToGuides.md)

**Comment by chao1995** [comment]
Since our repo is about process, many documentations can be formatted into a 'how to' question and its size will be large. And it's unclear what kind of questions are addressed in the 'how to' doc.

Even though we take the PR workflow part out to a separate document, we might still use the same fix as in the PR to make the list item linkable?

**Comment by damithc** [comment]
The use of auto-generated links as done is #82 is still a valid approach. Moving stuff to 'How to' doc can be considered separately.
