### ISSUE TITLE
Convert docs from markdown to asciidoc

### ISSUE THREAD

**Issue by pyokagan** [oss-generic/process#92]
**Rationale**

Our docs need toc generation and section numbering, which gfmd does not provide. Currently we are using workarounds (manual toc generation and section numbering), but that's not sustainable in the long run.

<sup>Real rationale: the typescript coding standard needs it :-P</sup>

**Comment by damithc** [comment]
@pyokagan what is the URL of the rendered version of the java coding standard?

**Comment by pyokagan** [comment]
@damithc If you want my staging version, it's at https://pyokagan.github.io/oss-generic-process/codingStandards/CodingStandard-Java.html

For the actual website, you'll need to set up Travis CI first (See https://github.com/oss-generic/process/pull/93#issuecomment-322669945), then it should be at https://oss-generic.github.io/process/codingStandards/CodingStandard-Java.html

**Comment by damithc** [comment]
I've set up the GITHUB_TOKEN

**Comment by pyokagan** [comment]
@damithc Alright. I see Travis has deployed the website to `gh-pages` successfully. I think the last thing that needs to be done is to go to Settings and change the GitHub pages branch from `master` to `gh-pages`.

**Comment by damithc** [comment]
Done. Thanks for the help (and the conversion) @pyokagan 💯
